In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline

In [ ]:
df = pd.read_csv('mental-state.csv')

In [ ]:
df.head()

,lag1_mean_0,lag1_mean_1,lag1_mean_2,lag1_mean_3,lag1_mean_d_h2h1_0,lag1_mean_d_h2h1_1,lag1_mean_d_h2h1_2,lag1_mean_d_h2h1_3,lag1_mean_q1_0,lag1_mean_q1_1,...,freq_669_3,freq_679_3,freq_689_3,freq_699_3,freq_709_3,freq_720_3,freq_730_3,freq_740_3,freq_750_3,Label
0,25.781648,33.836367,-92.769629,19.187957,-1.542262,0.197462,-119.561133,2.032654,21.596272,33.965587,...,0.000230,0.000351,0.000547,0.000381,0.000350,0.000453,0.000442,0.000325,0.000209,2.0
1,29.357891,26.792566,417.203910,19.472121,-38.797263,-16.897194,-29.368531,-9.055370,44.647424,40.893307,...,0.001671,0.000740,0.001122,0.000521,0.000624,0.000439,0.001249,0.000727,0.000801,2.0
2,28.451926,31.076434,72.231301,14.245938,-13.225057,-0.614138,-28.331698,-8.858742,31.450289,30.692883,...,0.000748,0.000569,0.000327,0.000197,0.000833,0.000909,0.000699,0.001165,0.000616,2.0
3,21.282184,19.985184,16.220094,39.787312,1.847866,0.670216,-1.820355,20.220724,21.404679,20.777411,...,0.000990,0.005644,0.006891,0.010546,0.009583,0.011158,0.008853,0.004551,0.002287,1.0
4,20.431516,28.982168,27.540246,19.960398,2.491458,-6.020503,-1.071166,2.655259,16.295039,32.658163,...,0.001659,0.014379,0.014492,0.002949,0.004575,0.008305,0.007202,0.006957,0.009836,2.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2479 entries, 0 to 2478
Columns: 989 entries, lag1_mean_0 to Label
dtypes: float64(989)
memory usage: 18.7 MB

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
lag1_mean_0,2479.0,23.584351,10.543938,-35.224945,18.732076,23.553828,27.759551,92.313766
lag1_mean_1,2479.0,27.060411,24.252348,-369.150109,21.328936,27.574535,32.247539,408.180215
lag1_mean_2,2479.0,20.452931,72.104439,-579.490660,17.124174,25.217098,30.746496,591.014113
lag1_mean_3,2479.0,11.526044,19.196870,-251.495367,6.541236,15.144375,20.589852,69.694520
lag1_mean_d_h2h1_0,2479.0,0.014449,13.382998,-75.143730,-4.647636,-0.140909,3.965898,104.963158
...,...,...,...,...,...,...,...,...
freq_720_3,2479.0,0.007998,0.007547,0.000041,0.002034,0.006005,0.011406,0.054104
freq_730_3,2479.0,0.007449,0.006937,0.000008,0.001985,0.005717,0.010768,0.060196
freq_740_3,2479.0,0.007307,0.007379,0.000036,0.002042,0.005300,0.010208,0.134037
freq_750_3,2479.0,0.007382,0.007276,0.000048,0.001964,0.005315,0.010330,0.071582
Label,2479.0,1.004437,0.815743,0.000000,0.000000,1.000000,2.000000,2.000000

In [ ]:
df['Label'] = np.where(df['Label'] == 0.0, 'relaxed',
                       np.where(df['Label'] == 1.0, 'concentrating', 'neutral'))

In [ ]:
X = df.drop(columns='Label')
y = df['Label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=300)),
    ('svc', SVC(degree=2, kernel='poly', C=1, gamma=0.01))
])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=300)),
                ('svc', SVC(C=1, degree=2, gamma=0.01, kernel='poly'))])

In [ ]:
y_pred = pipeline.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.969758064516129

In [ ]:
classification_report(y_test, y_pred)

'               precision    recall  f1-score   support\n\nconcentrating       0.95      0.96      0.96       167\n      neutral       0.98      0.99      0.98       162\n      relaxed       0.98      0.95      0.97       167\n\n     accuracy                           0.97       496\n    macro avg       0.97      0.97      0.97       496\n weighted avg       0.97      0.97      0.97       496\n'

In [179]:
import joblib

In [181]:
joblib.dump(pipeline, 'mental-state.pkl')

['mental-state.pkl']